
platform :ios, '11.4'

target 'UVCare' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UVCare
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'GTProgressBar'
end
